routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get( '/', 'HomeController@index' )->name( 'home' );

Route::group(
	[
		'prefix' => 'admin',
		'as' => 'admin.',
		'middleware' => ['auth'],
	],
	function () {

		Route::get( '/', 'Admin\HomeController@index' )->name( 'home' );

		Route::group([
			'prefix' => 'users',
			'as' => 'users.'
		],
		function(){
			Route::get('/paginate', 'UserController@paginate')->name('paginate');
			Route::get('/fetch_data', 'UserController@fetch_data');
			Route::get('/', 'UserController@index')->name('index');
			Route::get('/create/{user?}', 'UserController@create')->name('create');
			Route::post('/store/{user?}', 'UserController@store')->name('store');
			Route::get('/{user}', 'UserController@show')->name('show');
			Route::delete('/users/{user}/destroy', 'UserController@destroy')->name('destroy');
			Route::get('/{user}/edit', 'UserController@edit')->name('edit');
			Route::put('/{user}/update', 'UserController@update')->name('update');

			Route::group(['prefix' => '{user}'], function () {
				Route::post('/first', 'UserController@first')->name('first');
				Route::post('/up', 'UserController@up')->name('up');
				Route::post('/down', 'UserController@down')->name('down');
				Route::post('/last', 'UserController@last')->name('last');
			});
		});

	});

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\Support\Renderable;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return Renderable
     */
    public function index()
    {
        return view('admin.home');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/UserController.php
<?php


namespace App\Http\Controllers;


use App\Entity\User;
use Exception;
use Illuminate\Http\RedirectResponse;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
use Throwable;

class UserController extends Controller
{
	public function index()
	{
		$users = User::defaultOrder()->withDepth()->paginate(30);

		return view('admin.users.index', compact('users'));
	}

	public function paginate()
	{
		$users = User::defaultOrder()->withDepth()->paginate(30);

		return view('admin.users.paginate', compact('users'));
	}

	/**
	 * @param Request $request
	 *
	 * @return array|string
	 * @throws Throwable
	 */
	function fetch_data(Request $request)
	{
		$sort_by = $request->get('sortby');
		$sort_type = $request->get('sorttype');
		$query = $request->get('query');
		if($request->ajax())
		{
			$users = User::with('ancestors')
			             ->withDepth()
		                 ->where('id', 'like', '%'.$query.'%')
				         ->orWhere('full_name', 'like', '%'.$query.'%')
				         ->orWhere('email', 'like', '%'.$query.'%')
				         ->orderBy($sort_by, $sort_type)
			             ->paginate(30);
			return view('admin.users.pagination_data', compact('users'))->render();
		}

		return view('admin.users.paginate', compact('users'));
	}

	public function create(User $user)
	{
		$parent = $user->getParentId();

		return view('admin.users.create', compact('parent'));
	}

	/**
	 * @param Request $request
	 *
	 * @return RedirectResponse
	 * @throws ValidationException
	 */
	public function store(Request $request)
	{
		$this->validate($request, [
			'full_name' => 'required|string|max:255||unique:users',
			'email' => 'required|string|max:255|unique:users',
			'slug' => 'required|string|max:255|unique:users',
			'position' => 'required|string|max:255',
			'salary' => 'required|string|max:255',
			'password' => 'required|string|min:8'
		]);

		$user = User::create([
			'full_name' => $request['full_name'],
			'email' => $request['email'],
			'slug' => $request['slug'],
			'position' => $request['position'],
			'salary' => $request['salary'],
			'parent_id' => $request['parent'],
			'password' => Hash::make($request['password']),
		]);



		return redirect()->route('admin.users.show', $user);
	}

	public function show(User $user)
	{
		$users = User::where('parent_id', $user->id)->orderBy('full_name')->get();

		return view('admin.users.show', compact('user','users'));
	}

	public function edit(User $user)
	{
		return view('admin.users.edit', compact('user'));
	}

	/**
	 * @param User $user
	 * @param Request $request
	 *
	 * @return RedirectResponse
	 * @throws ValidationException
	 */
	public function update(User $user, Request $request)
	{
		$this->validate($request, [
			'photo' => 'nullable|image|mimes:jpg,png|max:5048',
			'full_name' => 'required|string|max:255',
			'email' => 'required|string|max:255',
			'slug' => 'required|string|max:255',
			'position' => 'required|string|max:255',
			'salary' => 'required|string|max:255',
		]);

		$path = null;
		$image = $request->file('photo');
		if ($request['photo'] !== null){
			$new_name = rand() . '.' . $image->getClientOriginalExtension();
			$image->move(public_path('build/images'), $new_name);
			$path = '/build/images/' . $new_name;
			$user->update(['photo' => $path]);
		}


		$user->update([
			'name' => $request['name'],
			'email' => $request['email'],
			'slug' => $request['slug'],
			'position' => $request['position'],
			'salary' => $request['salary']
		]);



		return redirect()->route('admin.users.show', $user);
	}

	public function first(User $user)
	{
		if ($first = $user->siblings()->defaultOrder()->first()) {
			$user->insertBeforeNode($first);
		}

		return redirect()->route('admin.users.index');
	}

	public function up(User $user)
	{
		$user->up();

		return redirect()->route('admin.users.index');
	}

	public function down(User $user)
	{
		$user->down();

		return redirect()->route('admin.users.index');
	}

	public function last(User $user)
	{
		if ($last = $user->siblings()->defaultOrder('desc')->first()) {
			$user->insertAfterNode($last);
		}

		return redirect()->route('admin.users.index');
	}
	/**
	 * @param User $user
	 *
	 * @return RedirectResponse
	 * @throws Exception
	 */
	public function destroy(User $user)
	{
		$user->delete();

		return redirect()->route('admin.users.index');
	}
}

resources/views/admin/_nav.blade.php
<ul class="nav nav-tabs mb-3">
    <li class="nav-item"><a class="nav-link{{ $page === '' ? ' active' : '' }}" href="{{ route('admin.home') }}">Dashboard</a></li>
    <li class="nav-item"><a class="nav-link{{ $page === 'adverts' ? ' active' : '' }}" href="{{ route('admin.users.index') }}">UsersTree</a></li>
    <li class="nav-item"><a class="nav-link{{ $page === 'banners' ? ' active' : '' }}" href="{{ route('admin.users.paginate') }}">UsersAjax</a></li>
</ul>

resources/views/admin/home.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                @include ('admin._nav', ['page' => 'users'])

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Home admin!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')

    <form method="POST" action="{{ route('admin.users.store') }}">
        @csrf
        <div class="form-group">
            <label for="full_name" class="col-form-label">Full Name</label>
            <input id="full_name" class="form-control{{ $errors->has('full_name') ? ' is-invalid' : '' }}" name="full_name" value="{{ old('full_name') }}" required>
            @if ($errors->has('full_name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('full_name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="email" class="col-form-label">E-Mail Address</label>
            <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>
            @if ($errors->has('email'))
                <span class="invalid-feedback"><strong>{{ $errors->first('email') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="slug" class="col-form-label">Slug</label>
            <input id="slug" type="text" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}" name="slug" value="{{ old('slug') }}" required>
            @if ($errors->has('slug'))
                <span class="invalid-feedback"><strong>{{ $errors->first('slug') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="salary" class="col-form-label">Salary</label>
            <input id="salary" type="text" class="form-control{{ $errors->has('salary') ? ' is-invalid' : '' }}" name="salary" value="{{ old('salary') }}" required>
            @if ($errors->has('salary'))
                <span class="invalid-feedback"><strong>{{ $errors->first('salary') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="position" class="col-form-label">Position</label>
            <input id="position" type="text" class="form-control{{ $errors->has('position') ? ' is-invalid' : '' }}" name="position" value="{{ old('position') }}" required>
            @if ($errors->has('position'))
                <span class="invalid-feedback"><strong>{{ $errors->first('position') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="password" class="col-form-label">Password</label>
            <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" value="{{ old('password') }}" required>
            @if ($errors->has('password'))
                <span class="invalid-feedback"><strong>{{ $errors->first('password') }}</strong></span>
            @endif
        </div>
        <input type="hidden"  name="parent" value="{{ $parent }}" required>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')

    <form method="POST" action="{{ route('admin.users.update', $user) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="photo" class="col-form-label">Photo</label>
            <input id="photo" type="file" class="form-control{{ $errors->has('photo') ? ' is-invalid' : '' }}" name="photo" value="{{ old('photo', $user->photo) }}">
            @if ($errors->has('photo'))
                <span class="invalid-feedback"><strong>{{ $errors->first('photo') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <label for="full_name" class="col-form-label">Full Name</label>
            <input id="full_name" class="form-control{{ $errors->has('full_name') ? ' is-invalid' : '' }}" name="full_name" value="{{ old('full_name', $user->full_name) }}" required>
            @if ($errors->has('full_name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('full_name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="email" class="col-form-label">E-Mail Address</label>
            <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email', $user->email) }}" required>
            @if ($errors->has('email'))
                <span class="invalid-feedback"><strong>{{ $errors->first('email') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="slug" class="col-form-label">Slug</label>
            <input id="slug" type="text" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}" name="slug" value="{{ old('slug', $user->slug) }}" required>
            @if ($errors->has('slug'))
                <span class="invalid-feedback"><strong>{{ $errors->first('slug') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="salary" class="col-form-label">Salary</label>
            <input id="salary" type="text" class="form-control{{ $errors->has('salary') ? ' is-invalid' : '' }}" name="salary" value="{{ old('salary', $user->salary) }}" required>
            @if ($errors->has('salary'))
                <span class="invalid-feedback"><strong>{{ $errors->first('salary') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="position" class="col-form-label">Position</label>
            <input id="position" type="text" class="form-control{{ $errors->has('position') ? ' is-invalid' : '' }}" name="position" value="{{ old('position', $user->position) }}" required>
            @if ($errors->has('position'))
                <span class="invalid-feedback"><strong>{{ $errors->first('position') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="mb-2">
        <a href="{{ route('admin.users.create') }}" class="btn btn-success">
            Create User
        </a>
    </div>
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>Photo</th>
            <th>Name</th>
            <th>Email</th>
            <th>Position</th>
            <th>Salary</th>
            <th>First Date</th>
        </tr>
        </thead>
        <tbody>

        @foreach ($users as $user)
            <tr>
                <td>
                    {{ $user->id }}
                </td>
                <td>
                    @for ($i = 0; $i < $user->depth; $i++)
                    &mdash;
                    @endfor
                    @if($user->photo !== null)
                        <img width="50px" height="50px" src="{{$user->photo }}" alt="photo">
                    @else
                        <img width="50px" height="50px" src="/build/images/user.png" alt="photo">
                    @endif
                </td>
                <td>
                    <a href="{{ route('admin.users.show', $user) }}">
                        {{ $user->full_name }}
                    </a>
                </td>
                <td>
                    {{ $user->email}}
                </td>
                <td>
                    {{ $user-> position }}
                </td>
                <td>
                    {{ $user-> salary }} $
                </td>
                <td>
                    {{ $user->created_at->format('d/m/Y')}}
                </td>
            </tr>
        @endforeach
        {{ $users->links() }}
        </tbody>
    </table>
    {{ $users->links() }}

@endsection

resources/views/admin/users/paginate.blade.php
@extends('layouts.app')

@section('content')
    <div>
        <a href="{{ route('admin.users.create') }}" class="btn btn-success">
            Create User
        </a>
    </div>

        <div id="table_data">
             @include('admin.users.pagination_data')
        </div>

@endsection

resources/views/admin/users/pagination_data.blade.php
<div class="col-md-3">
    <div class="form-group">
        <label for="search" class="col-form-label">Search</label>
        <input type="text" name="search" id="search" class="form-control" />
    </div>
    <div class="mb-2">
        <button id="start-search" class="btn btn-primary">
            Search
        </button>
    </div>
</div>
<div class="table-responsive">
    <div id="table-date">
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th class="sorting" data-sorting_type="asc" data-column_name="id" style="cursor: pointer">ID <span id="id_icon"></span></th>
                <th>Photo</th>
                <th class="sorting" data-sorting_type="asc" data-column_name="full_name" style="cursor: pointer">Full Name <span id="full_name_icon"></span></th>
                <th class="sorting" data-sorting_type="asc" data-column_name="position" style="cursor: pointer">Position<span id="position_icon"></span></th>
                <th class="sorting" data-sorting_type="asc" data-column_name="salary" style="cursor: pointer">Salary<span id="salary_icon"></span></th>
            </tr>
            </thead>
            <tbody>

            @foreach ($users as $user)
                <tr>
                    <td>
                        {{ $user->id }}
                    </td>
                    <td>
                        @for ($i = 0; $i < $user->depth; $i++)
                        &mdash;
                        @endfor
                        @if($user->photo !== null)
                            <img width="50px" height="50px" src="{{$user->photo }}" alt="photo">
                        @else
                            <img width="50px" height="50px" src="/build/images/user.png" alt="photo">
                        @endif
                    </td>
                    <td>

                        <a href="{{ route('admin.users.show', $user) }}">
                            {{ $user->full_name }}
                        </a>
                    </td>
                    <td>
                        {{ $user-> position }}
                    </td>
                    <td>
                        {{ $user-> salary }} $
                    </td>
                </tr>
            @endforeach
            {{ $users->links() }}
            </tbody>
        </table>
        {{ $users->links() }}
    </div>
</div>
<input type="hidden" name="hidden_page" id="hidden_page" value="1" />
<input type="hidden" name="hidden_column_name" id="hidden_column_name" value="id" />
<input type="hidden" name="hidden_sort_type" id="hidden_sort_type" value="asc" />
<script>
    $(document).ready(function(){

        function clear_icon()
        {
            $('#id_icon').html('');
            $('#full_name_icon').html('');
        }

        function fetch_data(page, sort_type, sort_by, query)
        {
            $.ajax({
                url:"/admin/users/fetch_data?page="+page+"&sortby="+sort_by+"&sorttype="+sort_type+"&query="+query,
                success:function(data)
                {
                    // $('tbody').html('');
                    $('#table_data').html(data)
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.status);
                    alert(xhr.responseText);
                    alert(thrownError);
                }
            })
        }

        $(document).on('click', '#start-search', function(){
            var query = $('#search').val();
            var column_name = $('#hidden_column_name').val();
            var sort_type = $('#hidden_sort_type').val();
            var page = $('#hidden_page').val();
            fetch_data(page, sort_type, column_name, query);
        });

        $(document).on('click', '.sorting', function(){
            var column_name = $(this).data('column_name');
            var order_type = $(this).data('sorting_type');
            var reverse_order = '';
            if(order_type == 'asc')
            {
                $(this).data('sorting_type', 'desc');
                reverse_order = 'desc';
                clear_icon();
                $('#'+column_name+'_icon').html('<i class="fas fa-angle-down"></i>');
            }
            if(order_type == 'desc')
            {
                $(this).data('sorting_type', 'asc');
                reverse_order = 'asc';
                clear_icon
                $('#'+column_name+'_icon').html('<span class="fas fa-angle-up"></span>');
            }
            $('#hidden_column_name').val(column_name);
            $('#hidden_sort_type').val(reverse_order);
            var page = $('#hidden_page').val();
            var query = $('#search').val();
            fetch_data(page, reverse_order, column_name, query);
        });

        $(document).on('click', '.pagination a', function(event){
            event.preventDefault();
            var page = $(this).attr('href').split('page=')[1];
            var column_name = $('#hidden_column_name').val();
            var sort_type = $('#hidden_sort_type').val();

            var query = $('#search').val();

            $('li').removeClass('active');
            $(this).parent().addClass('active');
            fetch_data(page, sort_type, column_name, query);
        });

    });
</script>

resources/views/admin/users/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex flex-row mb-3">
        <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-primary mr-1">Edit</a>
        <form method="POST" action="{{ route('admin.users.destroy', $user) }}" class="mr-1">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger">Delete</button>
        </form>
    </div>
    <table class="table table-bordered table-striped">
        <tbody>
        <tr>
            <th>
                Photo
            </th>
            <td>
                @if($user->photo !== null)
                     <img width="150px" height="150px" src="{{$user->photo }}" alt="photo">
                @else
                    <img width="150px" height="150px" src="/build/images/user.png" alt="photo">
                @endif
            </td>
        </tr>
        <tr>
            <th>ID</th><td>{{ $user->id }}</td>
        </tr>
        <tr>
            <th>Full Name</th><td>{{ $user->full_name }}</td>
        </tr>
        <tr>
            <th>Email</th><td>{{ $user->email }}</td>
        </tr>
        <tr>
            <th>Position</th><td>{{ $user->position }}</td>
        </tr>
        <tr>
            <th>Salary</th><td>{{ $user->salary }}</td>
        </tr>
        <tr>
            <th>Slug</th><td>{{ $user->slug }}</td>
        </tr>
        <tr>
            <th>First date</th><td>{{ $user->created_at }}</td>
        </tr>
        <tbody>
        </tbody>
    </table>

    <div>
        <a href="{{ route('admin.users.create', $user) }}" class="btn btn-success">
            Create User
        </a>
    </div>

    <h2 class="text-center">
        Children
    </h2>
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Name</th>
            <th>Slug</th>
        </tr>
        </thead>
        <tbody>

        @foreach ($users as $user)
            <tr>
                <td><a href="{{ route('admin.users.show', $user) }}">{{ $user->full_name }}</a></td>
                <td>{{ $user->slug }}</td>
            </tr>
        @endforeach

        </tbody>
    </table>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('breadcrumbs')
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Your site!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
    <ul class="nav nav-tabs mb-3">
{{--        <li class="nav-item"><a class="nav-link active" href="{{ route('cabinet.home') }}">Dashboard</a></li>--}}
        {{--        <li class="nav-item"><a class="nav-link" href="{{ route('cabinet.adverts.index') }}">Adverts</a></li>--}}
        {{--        <li class="nav-item"><a class="nav-link" href="{{ route('cabinet.favorites.index') }}">Favorites</a></li>--}}
        {{--        <li class="nav-item"><a class="nav-link" href="{{ route('cabinet.banners.index') }}">Banners</a></li>--}}
        {{--        <li class="nav-item"><a class="nav-link" href="{{ route('cabinet.profile.home') }}">Profile</a></li>--}}
        {{--        <li class="nav-item"><a class="nav-link" href="{{ route('cabinet.tickets.index') }}">Tickets</a></li>--}}
    </ul>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ mix('js/app.js', 'build') }}" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css">

    <!-- Styles -->
    <link href="{{ mix('css/app.css', 'build') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light shadow-sm">
            <div class="container">
                <a class="navbar-brand home" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->full_name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('admin.home') }}">Admin</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                @section('breadcrumbs', Breadcrumbs::render())
                @yield('breadcrumbs')
                @include('layouts.partials.flash')
                @yield('content')
            </div>
        </main>
        <footer>
            <div class="container">
                <div class="border-top pt-3">
                    <p>
                        &copy; {{ date('Y')}} -  Laravel User-Profile
                    </p>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>

resources/views/layouts/partials/flash.blade.php
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif

@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif

@if (session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
@endif

@if (session('info'))
    <div class="alert alert-info">
        {{ session('info') }}
    </div>
@endif